load(":mayhemfile.bzl", "mayhemfile")

# Generates a Mayhemfile
mayhemfile(
    name = "factor",
    project = "bintools",
    target = "factor",
    command = "/bin/factor",
    image = "ubuntu:latest"
)
